services:
  bot:
    container_name: flammel-discord-bot
    build:
      context: .
      dockerfile: ./Containerfile
    env_file:
      - path: ./.env
        required: false
    environment:
      NODE_ENV: production
    secrets:
      - bot_token
    volumes:
      - ./seyfert-logs:/seyfert-logs

secrets:
  bot_token:
    file: ./secrets/bot_token
