services:
  bot:
    container_name: flammel-discord-bot
    build:
      context: .
      dockerfile: ./Containerfile
    env_file:
      - path: ./.env
        required: false
    secrets:
      - bot_token

secrets:
  bot_token:
    file: ./secrets/bot_token
