services:
  bot:
    container_name: flammel-discord-bot
    build:
      context: .
      dockerfile: ./Containerfile
    secrets:
      - bot_token
      - application_id

secrets:
  bot_token:
    file: ./secrets/bot_token
  application_id:
    file: ./secrets/application_id
