services:
  bot:
    container_name: flammel-discord-bot
    build:
      context: .
    secrets:
      - "BOT_TOKEN"
      - "APPLICATION_ID"

secrets:
  BOT_TOKEN:
    file: ./BOT_TOKEN.txt
  APPLICATION_ID:
    file: ./APPLICATION_ID.txt
